version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app:cached
      - /app/node_modules
    env_file:
      - .env.docker
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: