version: "3.9"

services:
  mongo-test:
    image: mongo:6.0
    container_name: mongo-test-db
    restart: always
    volumes:
      - mongo-test-data:/data/db

  api-test:
    build: .
    container_name: api-test-runner
    depends_on:
      - mongo-test
    env_file:
      - .env.test
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm test

volumes:
  mongo-test-data: